from __future__ import annotations

# Compatibility facade. New code should import from fh_admin_tui.domain.*.
from fh_admin_tui.domain.change_summary import diff_summary_lines
from fh_admin_tui.domain.character_rules import (
    ARM_REPAIR_CONFIG,
    INFECTION_STATES,
    INFECTION_VARIABLES,
    LIMB_CUT_STATES,
    LIMB_REPAIR_CONFIG,
    PHYSICAL_CONDITION_STATES,
    actor_display_name,
    actor_ids,
    actor_status_lines,
    add_actor_to_party,
    add_skill,
    cure_infections,
    equipped_armor_ids,
    get_actor,
    heal_physical_conditions,
    party_actor_ids,
    restore_supported_arms,
    restore_supported_limbs,
    revive_actor,
    unequip_armor,
)
from fh_admin_tui.domain.inventory_rules import (
    OwnedEntry,
    add_quantity,
    inventory_key,
    inventory_map,
    list_owned_entries,
    set_quantity,
)
from fh_admin_tui.domain.save_validation import validate_data

__all__ = [
    "ARM_REPAIR_CONFIG",
    "INFECTION_STATES",
    "INFECTION_VARIABLES",
    "LIMB_CUT_STATES",
    "LIMB_REPAIR_CONFIG",
    "OwnedEntry",
    "PHYSICAL_CONDITION_STATES",
    "actor_display_name",
    "actor_ids",
    "actor_status_lines",
    "add_actor_to_party",
    "add_quantity",
    "add_skill",
    "cure_infections",
    "diff_summary_lines",
    "equipped_armor_ids",
    "get_actor",
    "heal_physical_conditions",
    "inventory_key",
    "inventory_map",
    "list_owned_entries",
    "party_actor_ids",
    "restore_supported_arms",
    "restore_supported_limbs",
    "revive_actor",
    "set_quantity",
    "unequip_armor",
    "validate_data",
]
